### ISSUE TITLE
enchantment got something wrong

### ISSUE THREAD

**Issue by langmouren1** [HelpChat/DeluxeMenus#128]
my server warns
`[DeluxeMenus] Enchantment SHARPNESS for item 18 in menu menu is not a valid enchantment name!`
when im trying to andd anchantments on my menu's items
```
  '18':
    material: grass_block
    slot: 18
    display_name: '&6test'   
    click_commands: 
    - '[player] menu'
    enchantments: 
    - SHARPNESS;1
    hide_enchantments: true
```
and this is my code.does it have something wrong?
