### ISSUE TITLE
Menu alignment not working (oraxen) when changing the X value (%oraxen_neg_shift_X%) the image coordinates do not change

### ISSUE THREAD

**Issue by Murslk** [HelpChat/DeluxeMenus#143]
```
open_command: menu
size: 54
menu_title: '%oraxen_neg_shift_8%&f%oraxen_menu%'
register_command: true
open_requirement:
  requirements:
      deny_commands:
        - ''
```

when changing the X value (%oraxen_neg_shift_X%) the image coordinates do not change
what is the command, operator for image alignment?
