### ISSUE TITLE
[Suggestion] Item Templates

### ISSUE THREAD

**Issue by FaultyFunctions** [HelpChat/DeluxeMenus#162]
It would be nice if we had item templates if you had to do multiple items that were very similar but one or two things were different. Would cut down on a lot of repetition which is a major pain point IMO with creating menus.

**Comment by iGabyTM** [comment]
Depending how you want the template to work, you may be able to use yaml anchors and aliases https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

**Comment by FaultyFunctions** [comment]
Oh wow I didn't know this was a thing! Thank you for pointing it out. Is this just standing YAML spec?

**Comment by NoltoxGit** [comment]
> Depending how you want the template to work, you may be able to use yaml anchors and aliases https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

Hello !
I just saw this issue and it is interesting.

However, I didn't fully understand how the templates work thanks to the site you sent:
Can you please send me a demo with deluxemenus to see how it works? :)

**Comment by NoltoxGit** [comment]
> Depending how you want the template to work, you may be able to use yaml anchors and aliases https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

Hello @iGabyTM!
I just saw this issue and your message, and it's look interesting.

However, I didn't fully understand how the templates work thanks to the site you sent:
Can you please send me a demo with deluxemenus to see how it works? :)

**Comment by BlitzOffline** [comment]
Hi @NoltoxGit, here's a simple example where I create a dirt item and then place it in 2 different slots and with 2 different display names:

```yml
definitions:
  items:
    dirt_test: &dirt_test
      material: dirt
      slot: 0
      display_name: "&aMY DIRT!"


menu_title: '&fDIRT'
open_command: dirt
size: 9
items:
  dirt1: *dirt_test   # THIS ITEM WILL HAVE THE SAME PROPERTIES AS THE ONE DEFINED ABOVE
  dirt2:              # THIS ITEM WILL OVERRIDE THE SLOT AND DISPLAY NAME
    <<: *dirt_test
    slot: 1
    display_name: "&cMY OTHER DIRT!"
```

![Image](https://github.com/user-attachments/assets/5be9405c-5a2b-4566-ab01-d567b8d51e71)
![Image](https://github.com/user-attachments/assets/9d0b887e-eb35-47b6-9c13-839af6834fb3)

Closing this issue.
