### ISSUE TITLE
Args not work within placeholder

### ISSUE THREAD

**Issue by EterLuu** [HelpChat/DeluxeMenus#177]
I have used the latest development builds ([DeluxeMenus-1.14.1-DEV-196.jar](https://ci.extendedclip.com/job/DeluxeMenus/lastSuccessfulBuild/artifact/build/libs/DeluxeMenus-1.14.1-DEV-196.jar)) and the following example menu configuration.

```yaml
menu_title: 'Ex points'
open_command:
  - expoints

update_interval: 1
size: 54
register_command: true
args:
- type
- number

items:
  # Slot 40: Exchange
  'exchange':
    material: diamond
    slot: 40
    priority: 2
    update: true
    amount: 1
    display_name: "&d♪ &b&lStart to exchange"
    click_requirement:
      requirements:
        has_enough_money:
          type: ">="
          input: "%playerpoints_points%"
          output: "{number}"
        not_negative:
          type: ">="
          input: "{number}"
          output: "1"
      deny_commands:
        - "[message] &7[&6&l!&7] &cYou have no enough points！"
    click_commands:
      - "[sound] UI_BUTTON_CLICK"
      - "[close]"
      - "[console] points take %player_name% {number}"
      - "[console] si give soundstone %math_0_{number}*5% %player_name% false"
    view_requirement:
      requirements:
        exchange:
         type: "string equals"
         input: "{type}"
         output: "points"
    lore:
      - ""
      - "&f&l• &6Click to get&d %math_0_{number}*5% &3soundstone(s)"
      - ""
```

Where the placeholder `%math_0_{number}*5%` not updated properly as it used to be normal, and the error log is as following.

```
[13:33:00 WARN]: [PlaceholderAPI] [math] Invalid Placeholder detected!
[13:33:00 WARN]: [PlaceholderAPI] [math] Placeholder: %math_0_{number}*5%
[13:33:00 WARN]: [PlaceholderAPI] [math] Cause:       '{number}*5' is not a valid Math expression.
```

The math expansion can be downloaded [here](https://api.extendedclip.com/expansions/math/).
