### ISSUE TITLE
values

### ISSUE THREAD

**Issue by teslabars** [HelpChat/DeluxeMenus#179]
Hello. How to enter a range of values ito output parametr. In example:

 '13':
    material: flint_and_steel
    hide_attributes: true
    HIDE_DESTROYS: true
    data: 0
    slot: 35
    priority: 1
    display_name: '&eDelete all items in inventory'
    lore:
      - '&f/clear'
    left_click_commands:
      - '[close]'     
      - '[player] clear'
    view_requirements:
      requirements:
        prover:
          type: string equals
          input: '%player_empty_slots%'
          output: 35-0
  '13a':
    material: flint_and_steel
    hide_attributes: true
    HIDE_DESTROYS: true
    priority: 2
    data: 0
    slot: 35
    display_name: '&4Your inventory is empty!'
    view_requirements:
      requirements:
        prover:
          type: string equals
          input: '%player_empty_slots%'
          output: 36

**Comment by BlitzOffline** [comment]
Instead of using the `string equals` requirement, you should use the comparator requirements. In your example it would look something like this:

```yml
view_requirement:
  requirements:
    prover1:
      type: '>='
      input: '%player_empty_slots%'
      output: 0
    prover2:
      type: '<='
      input: '%player_empty_slots%'
      output: 35
```

You can read more about the 'comparator' requirement types (and about any other requirement type) here: <https://wiki.helpch.at/helpchat-plugins/deluxemenus/options-and-configurations/requirements#comparators>
