### ISSUE TITLE
bug unknown cmd

### ISSUE THREAD

**Issue by GG-MD** [HelpChat/DeluxeMenus#193]
1. dmenu reload
2. unknown cmd.... hmmm

menu:
```
menu_title: '&#ff404b🪓 &8Punish &f→ &#3eb7e2{player}'
open_command:
 - punish
args:
- player
register_command: true
args_usage_message: "&8» &7Use /punish nickname"
size: 53
open_commands:
  - '[sound] UI_LOOM_SELECT_PATTERN 1 1'
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: example.wadawd
  deny_commands:
    - '[console] title %player_name% times 5 60 5'
    - '[console] title %player_name% title {"text":"Error","bold":true,"color":"red"}'
    - '[console] title %player_name% subtitle {"text":"NOT ACCESS"}'
    - '[sound] ENTITY_WANDERING_TRADER_NO 2 1'
items:
 '1':
  material: head-%player_name%
  slot: 4
  update: true
  item_flags: [HIDE_ATTRIBUTES]
  display_name: '&eINFO'
#..... etc 
```
