### ISSUE TITLE
Fix has permission requirement

### ISSUE THREAD

**Issue by Wasdergingame** [HelpChat/DeluxeMenus#203]
I need to use the "has permission" type of requirements, but it doesn't work, regardless of whether the player has permission or not, it doesn't show the item. I grant permissions through LuckPerms. Here is a part of the code with this:
```
view_requirement:
      requirements:
        perm:
          type: has permission
          permission: "badges.admin"
```

**Comment by Tanguygab** [comment]
send your entire menu

**Comment by Wasdergingame** [comment]
```
#  A DeluxeMenus advanced configuration guide
#=========================================================
menu_title: '&8> &eБаджи'
size: 27
items:
  'clown':
    material: head-kaba4ki
    slot: 0
    display_name: '&cК&fл&cо&fу&cн'
    lore:
      - '&7Бадж, доступный всем игрокам'
    left_click_commands:
      - "[console] lp user %player_name% parent remove clown"
  'admin':
    material: command_block
    slot: 1
    display_name: '&c✘ &f- &4Админ'
    lore:
      - '&7Бадж, доступный только администрации.'
    priority: 1
    view_requirement:
      requirements:
        perm:
          type: has permission
          permission: "badges.admin"
    left_click_commands:
      - '[console] lp user %player_name% parent remove admin'
  'admin_noperm':
    material: command_block
    slot: 1
    display_name: '&7Админ - &cнедоступно'
    lore:
      - '&7Бадж, доступный только администрации.'
    left_click_commands:
      - '[message] У вас нет доступа к этому баджу!'
      - '[close]'
  'exit':
    material: red_wool
    slot: 26
    display_name: '&f Назад'
    left_click_commands:
      - '[openguimenu] badges'
```
