### ISSUE TITLE
Comments in config.yml are modified when reloading or restarting the plugin

### ISSUE THREAD

**Issue by NoltoxGit** [HelpChat/DeluxeMenus#209]
### Bug Description
When adding comments to the `config.yml` file of the DeluxeMenus plugin, and then reloading the plugin with `/deluxemnus reload` or restarting the server, the plugin rewrites the file by adding spaces before the existing comments.

#### Example before reload/restart:
```yml
# DeluxeMenus 1.14.1-Release main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/helpchat-plugins/deluxemenus

metas_list_page_size: 15
use_admin_commands_in_menus_list: true
menus_list_page_size: 8
debug: HIGHEST
check_updates: false
gui_menus:
  menu:
    file: menu_qui_fait_menu.yml

# #########################################
# - MAIN MENUS -
# ########################################

  histoire-blade:
    file: _MENUS_DIVERS/histoire-blade.yml
```

#### Example after reload/restart:
```yml
# DeluxeMenus 1.14.1-Release main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/helpchat-plugins/deluxemenus

metas_list_page_size: 15
use_admin_commands_in_menus_list: true
menus_list_page_size: 8
debug: HIGHEST
check_updates: false
gui_menus:
  menu:
    file: menu_qui_fait_menu.yml

  # #########################################
  # - MAIN MENUS -
  # ########################################

  histoire-blade:
    file: _MENUS_DIVERS/histoire-blade.yml
```

### Impact
This behavior changes the structure of comments in the configuration file, making it harder to read, especially when comments are used as section markers. Ideally, the plugin should not alter the indentation or spacing of user-added comments when reloading or restarting.

### Suggestion
It would be better if the configuration file reading/writing process did not modify the structure or indentation of comments added by the user.

### Useful Information
- Plugin version: 1.14.1-Release
- Platform: Leaf 1.21.4
- Affected file: `config.yml`
- Command used: `/deluxemnus reload`

Thank you for your help!
