### ISSUE TITLE
Better Meta System

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#21]
**Overall:** 
Consider a more streamlined approach for Deluxemenus by introducing a direct variable/meta system within the plugin. This would eliminate the reliance on the current meta storage in the `playerdata` folder, which can pose challenges in managing meta IDs and values. My suggestion involves creating a dedicated meta folder within Deluxemenus, where data names associated with non null meta values, and will be stored for at least one player that had value on that meta, which makes the new system more efficiencyt and reducing vulnerability to world file changes.

**Example:** 
• You run the `[meta]` action to set a meta for the player.
• When the command runs, it checks that this meta doesn't exist on the folder so it will create a yml file for it.
• [meta] set %player_name% FynnyCube STRING FUNNYCUBE IS THE BEST ADMIN
• File created: `FunnyCube.yml`

* The file could be something like that:
```yml 
TYPE: STRING
DEFAULT: null  
PLAYER: YES/NO
VALUES: 
  - %player_uuid% : FUNNY CUBE IS THE BEST ADMIN
 ``` 

* Notes: 
The `DEFAULT` value of that meta for every user when they do `%deluxemenus_meta_FunnyCube_STRING%` so there is no need anymore to specify it at the end. Additionally that value can also be changed via the config. The default value for the string can be null and for integer 0. 

The `PLAYER` also introduce a new method of meta that i will explain a bit later. But what it means is that this is a meta for each user individually. When player is set to `no` then it means that kind of meta specifically is a global one, and it will be treated as global for all the users. And the value could be instead:
```
VALUES: 
  - global: Hello
```
And this value like i said will be the same for all the users on the server.

Another cool addition could be `meta_requirement:` which can be used in the meta files alone and would be similar to the way the normal requirements work so;
```yml
TYPE: STRING
DEFAULT: null
PLAYER: no
meta_requirement: 
  requirements: 
    cube:
      type: 'string contains' 
      input: '%player_name%'
      output: 'cube'
VALUES: 
  - global: Hello 
 ```
 This wil still be a global meta but it will make it only accessible to certain people who have `cube` in their name. So when the players has `cube` in their name, it will return `Hello` for them, the ones that don't, will return null. This Overall i think it's a very nice addition for teams, guilds, island teams, parties, gangs, and everywhere were people can be a group. 

Additional stuff: 
`/dm edit <meta> <player:yes/no>` - Possible to change the value from player to global 
`/dm meta list`- Shows every meta ID 
`/dm meta <user>  list` - Shows all the meta and their value that the user has in a huge string like the one u do on `/dm list` (FunnyCube:STRING:Hello)
