### ISSUE TITLE
Display Light Levels - Addition 

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#23]
Deluxemenus doesn't currently support the display of the light levels. So the
```yml
material: light
nbt_ints:
  - "BlockStateTag.level:8"
```
won't return the correct light level to the material. Would be cool to get added too
