### ISSUE TITLE
Add slot placeholder that can be used in items

### ISSUE THREAD

**Issue by cj89898** [HelpChat/DeluxeMenus#25]
Would love to see a `$slot$` placeholder that can be used in item name/lore/actions/etc.

Example:
```yml
filler:
  material: stone
  display_name: 'Slot: $slot$'
  slots:
  - 0-54
```
