### ISSUE TITLE
Wrong material display

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#51]
These following material options return `STONE` instead of `AIR` as a display for the item, when the slot is empty.
`armor_helmet, armor_chestplate, armor_leggings, armor_boots`

_Example Menu:_
```yml
menu_title: '&8Stone'
size: 9
items:
  'armor_helmet':
    material: armor_helmet
    slot: 0
  'armor_chestplate':
    material: armor_chestplate
    slot: 1
  'armor_leggings':
    material: armor_leggings
    slot: 2
  'armor_boots':
    material: armor_boots
    slot: 3
```
