### ISSUE TITLE
Suggestion: new click option

### ISSUE THREAD

**Issue by ClickErrorxD** [HelpChat/DeluxeMenus#87]
It would be insanely useful for a new option that when an icon is clicked, it'll open the player's last deluxemenus menu. For example `[openlastmenu] true`.

**Comment by BlitzOffline** [comment]
Hello. The latest development builds of DeluxeMenus have added a `%deluxemenus_last_menu%` placeholder. You can combine this with the `[openguimenu]` action to achieve the same functionality. You can also add a click requirement to verify that a "last menu" exists.

```yml
click_commands:
- '[openguimenu] %deluxemenus_last_menu%'
click_requirement:
  requirements:
    type: '!string equals ignorecase'
    input: '%deluxemenus_last_menu%'
    output: ''
```

You can find the development builds of DeluxeMenus here: https://ci.extendedclip.com/job/DeluxeMenus/
