### ISSUE TITLE
Hide attributes is not working for spawners

### ISSUE THREAD

**Issue by msmanui** [HelpChat/DeluxeMenus#91]
Tested with lastest dev -> DeluxeMenus-1.14.1-DEV-178.jar

```
  'spawfnerb2':
    material: spawner
    slot: 38
    priority: 3
    hide_attributes: true
    display_name: '&#F5DEB3&lENDERMAN SPAWNER'
    left_click_commands:
    - '[close]'
```
