### ISSUE TITLE
Add cooldown time

### ISSUE THREAD

**Issue by 1470429149** [HelpChat/DeluxeMenus#94]
I think this is a very necessary feature and we should add a global cooldown
When players use a cheat client, repeatedly clicking on a single menu will take up a lot of server resources.

**Comment by BlitzOffline** [comment]
Having cooldowns built into DeluxeMenus is not a bad idea.

Notes: 
- Built-in cooldowns should be ephemeral (persist until the plugin is unloaded)
- Should be one of the first validations done
- Should be global, per menu and item
- Should have a maximum value (suggestion: 3600 seconds / 72000 ticks)
People who want longer cooldowns should use existing solutions such as MasterCooldowns or temporary permissions.

## Temporary solution
How to create cooldowns using [MasterCooldowns](https://www.spigotmc.org/resources/72145/):
1. Start by creating a requirement (view/click/open)
```yaml
requirements:
  cooldown:
    type: string equals
    input: '%mcd_isinactive_COOLDOWN-ID%'
    output: 'Yes'
  deny_commands:
  - '[message] &cTry again in %mcd_left_formatted_COOLDOWN-ID%, you are on cooldown!'
```
2. Add the cooldown (e.g. on click)
`[console] mcd add %player_name% COOLDOWN-ID duration`

This is not the only way to create cooldowns for DM, temporary permissions being another example.
